FROM nvidia/cuda:10.2-devel-ubuntu18.04

RUN apt-get update  && apt-get install -y gfortran build-essential \
    && apt-get install -y curl git ninja-build && rm -rf /var/lib/apt/lists/*

ENV PATH=/opt/miniconda3/bin:${PATH} CONDA_PREFIX=/opt/miniconda3

RUN curl -LO https://repo.anaconda.com/miniconda/Miniconda3-py37_4.8.3-Linux-x86_64.sh && \
    bash Miniconda3-py37_4.8.3-Linux-x86_64.sh -p /opt/miniconda3 -b && \
    rm Miniconda3-py37_4.8.3-Linux-x86_64.sh && \
    conda install pytorch=1.7.0 cudatoolkit=10.2 cudnn -c pytorch -y && \
    conda install conda-verify conda-build mkl-include cmake ninja -c anaconda -y && \
    conda clean -afy

RUN pip install --no-cache-dir OpenNMT-py==1.1.0 docopt onnxruntime-gpu==1.3.0 transformers==3.4.0 matplotlib


# build turbo
# RUN mkdir -p /src && cd /src && git clone https://github.com/Tencent/TurboTransformers.git --recursive && cd ./TurboTransformers && \
#    sh ./tools/build_and_run_unittests.sh $PWD -DWITH_GPU=ON

# build PETS

RUN mkdir -p /src

WORKDIR /workspace
